"""incluimos la columna de pais

Revision ID: 687e7b259740
Revises: 
Create Date: 2023-02-03 01:53:21.423524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687e7b259740'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pais', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personas', schema=None) as batch_op:
        batch_op.drop_column('pais')

    # ### end Alembic commands ###
